const programKeahlian = [
    "Teknik Perawatan Gedung",
    "Konstruksi dan Perawatan Bangunan Sipil",
    "Teknik Konstruksi dan Perumahan",
    "Desain Pemodelan dan Informasi Bangunan",
    "Teknik Furnitur",
    "Teknik Mesin",
    "Teknik Otomotif",
    "Teknik Pengelasan dan Fabrikasi Logam",
    "Teknik Logistik",
    "Teknik Elektronika",
    "Teknik Pesawat Udara",
    "Teknik Konstruksi Kapal",
    "Kimia Analisis",
    "Teknik Kimia Industri",
    "Teknik Tekstil",
    "Teknik Ketenagalistrikan",
    "Teknik Energi Terbarukan",
    "Teknik Geospasial",
    "Teknik Geologi Pertambangan",
    "Teknik Perminyakan",
    "Pengembangan Perangkat Lunak dan Gim",
    "Teknik Jaringan Komputer dan Telekomunikasi",
    "Layanan Kesehatan",
    "Teknik Laboratorium Medik",
    "Teknologi Farmasi",
    "Pekerjaan Sosial",
    "Agribisnis Tanaman",
    "Agribisnis Ternak",
    "Agribisnis Perikanan",
    "Usaha Pertanian Terpadu",
    "Agriteknologi Pengolahan Hasil Pertanian",
    "Kehutanan",
    "Teknika Kapal Penangkapan Ikan",
    "Nautika Kapal Penangkapan Ikan",
    "Teknika Kapal Niaga",
    "Nautika Kapal Niaga",
    "Pemasaran",
    "Manajemen Perkantoran dan Layanan Bisnis",
    "Akuntansi dan Keuangan Lembaga",
    "Usaha Layanan Pariwisata",
    "Perhotelan",
    "Kuliner",
    "Kecantikan dan Spa",
    "Seni Rupa",
    "Desain Komunikasi Visual",
    "Desain dan Produksi Kriya",
    "Seni Pertunjukan",
    "Broadcasting dan Perfilman",
    "Animasi",
    "Busana"
];
