const mataPelajaranSdArray = [
  "Pendidikan Agama Islam dan Budi Pekerti",
  "Pendidikan Agama Kristen dan Budi Pekerti",
  "Pendidikan Agama Katolik dan Budi Pekerti",
  "Pendidikan Agama Buddha dan Budi Pekerti",
  "Pendidikan Agama Hindu dan Budi Pekerti",
  "Pendidikan Agama Konghucu dan Budi Pekerti",
  "Pendidikan Pancasila",
  "Bahasa Indonesia",
  "Matematika",
  "Pendidikan Jasmani Olahraga dan Kesehatan",
  "Seni Musik",
  "Seni Rupa",
  "Seni Teater",
  "Seni Tari",
  "Bahasa Inggris",
  "Muatan Lokal",
];
const mataPelajaranSmpArray = [
  "Pendidikan Agama Islam dan Budi Pekerti",
  "Pendidikan Agama Kristen dan Budi Pekerti",
  "Pendidikan Agama Katolik dan Budi Pekerti",
  "Pendidikan Agama Buddha dan Budi Pekerti",
  "Pendidikan Agama Hindu dan Budi Pekerti",
  "Pendidikan Agama Konghucu dan Budi Pekerti",
  "Pendidikan Pancasila",
  "Bahasa Indonesia",
  "Matematika",
  "Ilmu Pengetahuan Alam",
  "Ilmu Pengetahuan Sosial",
  "Bahasa Inggris",
  "Pendidikan Jasmani Olahraga dan Kesehatan",
  "Informatika",
  "Seni Musik",
  "Seni Rupa",
  "Seni Teater",
  "Seni Tari",
  "Prakarya (Budidaya, Kerajinan, Rekayasa, atau Pengolahan)",
  "Muatan Lokal",
];
const mataPelajaranSmaArray = [
  "Pendidikan Agama Islam dan Budi Pekerti",
  "Pendidikan Agama Kristen dan Budi Pekerti",
  "Pendidikan Agama Katolik dan Budi Pekerti",
  "Pendidikan Agama Buddha dan Budi Pekerti",
  "Pendidikan Agama Hindu dan Budi Pekerti",
  "Pendidikan Agama Konghucu dan Budi Pekerti",
  "Pendidikan Pancasila",
  "Bahasa Indonesia",
  "Matematika",
  "Ilmu Pengetahuan Alam",
  "Ilmu Pengetahuan Sosial",
  "Bahasa Inggris",
  "Pendidikan Jasmani Olahraga dan Kesehatan",
  "Informatika",
  "Seni Musik",
  "Seni Rupa",
  "Seni Teater",
  "Seni Tari",
  "Prakarya (Budidaya, Kerajinan, Rekayasa, atau Pengolahan)",
  "Muatan Lokal",
  "Biologi",
  "Kimia",
  "Fisika",
  "Matematika tingkat lanjut",
  "Sosiologi",
  "Ekonomi",
  "Geografi",
  "Antropologi",
  "Bahasa Indonesia tingkat lanjut",
  "Bahasa Inggris tingkat lanjut",
  "Bahasa Korea",
  "Bahasa Arab",
  "Bahasa Mandarin",
  "Bahasa Jepang",
  "Bahasa Jerman",
  "Bahasa Prancis",
  "Prakarya dan Kewirausahaan (budidaya, kerajinan, rekayasa, atau pengolahan)",
];
